### ISSUE TITLE
Fails to build with liblouis 3.3

### ISSUE THREAD

**Issue by sthibaul** [liblouis/liblouisutdml#37]
Hello,

The current git doesn't builld with liblouis3.3 , let alone released versions :)

The issues we have spotted in Debian are
- the logMessage -> _lou_logMessage renaming, 
- the use of ascii8 in louisutdml.h which conflicts with liblouis'
- the use of FileInfo in readconfig.c and semantics.c which conflict with liblouis'

Samuel

**Comment by egli** [comment]
Thanks for the report. Unfortunately liblouisutdml is basically unmaintained. We move the liblouis API forward but fail to synchronize liblouisutdml with it.

Attila has provided a PR that fixes most of the issues you mention (#35). I have some issues with the PR but hope to merge it eventually.

**Comment by sthibaul** [comment]
Mmm, it's unfortunate if it's unmaintained. To my knowledge, it's the best (as in: up to date, well integrated, etc.) we can have to emboss html, libreoffice / msoffice documents and such.

How was it maintained initially? Did the focus of the maintenance perhaps change due to a company or research project interest change?

**Comment by egli** [comment]
The original maintainer (@johnjboyer) retired and a bunch of people took over maintenance of liblouis (as we use that in production). Nobody stepped forward to maintain liblouisutdml.

I can try to at least keep it compatible with liblouis and maybe also produce a release, but since I do not use it personally or professionally it is hard for me to justify the time it takes to do so.

**Comment by egli** [comment]
@sthibaul I believe that most of the problems have been fixed now with the merge of #38. Can you try and see if this warrants a new release?

**Comment by sthibaul** [comment]
Yes, it builds fine for me with the fixes from #38
