### ISSUE TITLE
Mixed fractions are not converted correctly to Nemeth

### ISSUE THREAD

**Issue by NSoiffer** [liblouis/liblouisutdml#61]
The mixed fraction test (`mathml_nemeth/mfrac_03.test`) fails:

Image | ![image](https://user-images.githubusercontent.com/1545836/62982356-bf38b780-bde0-11e9-9d76-68f3d353bb2a.png)
------------ | -------------
Output | `#4_?3/8#`
Expected | `#4_?3/8_#`

The closing indicator for mixed fractions is missing.

**Comment by hammera** [comment]
@NSoiffer, the tests/mathml_nemeth/mfrac_03.test in #96 pull request related feature branch are passed now.
If the #96 pull request are final merged, this issue will be resolved.

I will looks the #88 related failures with @norbertmarkus new nemeth table related modifications.

@norbertmarkus  active working now the nemeth.ctb table related fixes, now on the development branch from the 219 tests are 149 tests passed, 0 test failed or errored, and only 70 tests are xfailed when we examine the tests with Liblouis 3.26.0 version.

Hope this information help for yu.

Kind regards,

Attila

**Comment by hammera** [comment]
fixed #96 
mathml_nemeth/mfrac_03.test are passed with Liblouis UTDML latest master branch version, because #96 large Nemeth tables related pull request are merged in october 18.
@NSoiffer, if this issue are not closing automatically, please close this issue, or anybody with have permission close this issue.

Kind regards,

Attila
